Update consignment service with view feature
Here, we have created a new method on our service called
GetConsignments ; a new GetRequest as a stub ; and a consignments field
to our response message.

We expect to see an error here:

  $ go run main.go
  ./main.go:72: cannot use service literal (type *service) as type
  go_micro_srv_consignment.ShippingServiceServer in argument to
  go_micro_srv_consignment.RegisterShippingServiceServer:
          *service does not implement
  go_micro_srv_consignment.ShippingServiceServer (missing GetConsignments
  method)